# Generated by Django 4.0.2 on 2022-06-23 18:03

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
        migrations.AlterModelOptions(
            name='main_anime',
            options={'ordering': ['-added']},
        ),
        migrations.AddField(
            model_name='main_anime',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='main_anime',
            name='link',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AddField(
            model_name='main_anime',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('RC', 'romcom'), ('SC', 'scifi'), ('A', 'action')], max_length=2),
        ),
    ]
