# Generated by Django 4.0.2 on 2022-06-23 18:08

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_video_alter_main_anime_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime_episodes',
            options={'ordering': ['-added']},
        ),
        migrations.AlterModelOptions(
            name='main_anime',
            options={},
        ),
        migrations.RemoveField(
            model_name='main_anime',
            name='added',
        ),
        migrations.RemoveField(
            model_name='main_anime',
            name='link',
        ),
        migrations.RemoveField(
            model_name='main_anime',
            name='title',
        ),
        migrations.AddField(
            model_name='anime_episodes',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='anime_episodes',
            name='link',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AddField(
            model_name='anime_episodes',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('SC', 'scifi'), ('A', 'action'), ('RC', 'romcom')], max_length=2),
        ),
    ]
