# Generated by Django 4.0.2 on 2022-06-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_anime_episodes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime_episodes',
            options={'ordering': ['added']},
        ),
        migrations.RemoveField(
            model_name='anime_episodes',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='anime_episodes',
            name='title',
        ),
        migrations.AddField(
            model_name='anime_episodes',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('A', 'action'), ('RC', 'romcom'), ('SC', 'scifi')], max_length=2),
        ),
    ]
