# Generated by Django 4.0.2 on 2022-06-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_anime_episodes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Homedescription', models.TextField(blank=True)),
                ('home_anime_name', models.CharField(blank=True, max_length=50)),
                ('homepage_thumbnail', models.ImageField(upload_to='animeimg')),
            ],
        ),
    ]
