# Generated by Django 4.0.2 on 2022-06-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('A', 'action'), ('SC', 'scifi'), ('RC', 'romcom')], max_length=2),
        ),
    ]
