# Generated by Django 4.0.2 on 2022-06-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_main_anime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('A', 'action'), ('RC', 'romcom'), ('SC', 'scifi')], max_length=2),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='episode_thumbnail',
            field=models.ImageField(height_field='2160', upload_to='animeimg', width_field='3840px'),
        ),
    ]
