# Generated by Django 4.0.2 on 2022-06-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_main_anime_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime_episodes',
            options={},
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('SC', 'scifi'), ('RC', 'romcom'), ('A', 'action')], max_length=2),
        ),
    ]
