# Generated by Django 4.0.2 on 2022-06-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_anime_episodes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime_episodes',
            options={'ordering': ['added']},
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('A', 'action'), ('SC', 'scifi'), ('RC', 'romcom')], max_length=2),
        ),
    ]
