# Generated by Django 4.0.5 on 2022-07-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_main_anime_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_anime',
            name='anime_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('A', 'action'), ('RC', 'romcom'), ('SC', 'scifi')], max_length=2),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
