# Generated by Django 4.0.5 on 2022-07-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_main_anime_category_anime_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_episodes',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='app.anime_details'),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('SC', 'scifi'), ('RC', 'romcom'), ('A', 'action')], max_length=2),
        ),
    ]
