# Generated by Django 4.0.5 on 2022-07-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_anime_episodes_anime_alter_main_anime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_episodes',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='app.main_anime'),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('RC', 'romcom'), ('A', 'action'), ('SC', 'scifi')], max_length=2),
        ),
    ]
