# Generated by Django 4.0.5 on 2022-07-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_anime_episodes_anime_alter_main_anime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('TR', 'TopRated'), ('AB', 'AllTimeBest'), ('N', 'Newest')], max_length=2),
        ),
    ]
