# Generated by Django 4.0.5 on 2022-07-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_main_anime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('N', 'Newest'), ('AB', 'AllTimeBest'), ('TR', 'TopRated')], max_length=2),
        ),
    ]
