# Generated by Django 4.0.5 on 2022-07-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_main_anime_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedb', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('N', 'Newest'), ('TR', 'TopRated'), ('AB', 'AllTimeBest')], max_length=2),
        ),
    ]
