# Generated by Django 4.0.5 on 2022-07-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_feedb_feedback_feedbck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('TR', 'TopRated'), ('N', 'Newest'), ('AB', 'AllTimeBest')], max_length=2),
        ),
    ]
