# Generated by Django 4.0.5 on 2022-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_anime_details_description_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedbck',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('TR', 'TopRated'), ('N', 'Newest'), ('AB', 'AllTimeBest')], max_length=2),
        ),
    ]
