# Generated by Django 4.0.5 on 2022-07-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_main_anime_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_details',
            name='anime_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='app.main_anime'),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('N', 'Newest'), ('TR', 'TopRated'), ('AB', 'AllTimeBest')], max_length=2),
        ),
    ]
