# Generated by Django 4.0.5 on 2022-07-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_anime_details_anime_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('TR', 'TopRated'), ('AB', 'AllTimeBest'), ('N', 'Newest')], max_length=2),
        ),
    ]
