# Generated by Django 4.0.5 on 2022-07-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_main_anime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_details',
            name='img_details',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('N', 'Newest'), ('TR', 'TopRated'), ('AB', 'AllTimeBest')], max_length=2),
        ),
    ]
