# Generated by Django 4.0.5 on 2022-07-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_main_anime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='homepage_thumbnail',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='category',
            field=models.CharField(choices=[('TR', 'TopRated'), ('N', 'Newest'), ('AB', 'AllTimeBest')], max_length=2),
        ),
        migrations.AlterField(
            model_name='main_anime',
            name='episode_thumbnail',
            field=models.URLField(),
        ),
    ]
