# Generated by Django 4.0.5 on 2022-11-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_video_alter_main_anime_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime_episodes',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='anime_names',
        ),
        migrations.DeleteModel(
            name='anime_details',
        ),
        migrations.DeleteModel(
            name='anime_episodes',
        ),
        migrations.DeleteModel(
            name='main_anime',
        ),
    ]
